title: Your Site Title
description: A simple description of your site.
theme: jekyll-theme-primer

# Optional, depending on your needs
markdown: kramdown

# Disable SCSS converter if not using SCSS
sass:
  style: compressed
