url: "https://kavikavinesh.github.io" # Replace 'username' with your GitHub username
baseurl: "/kavinesh_portfolio"  # Replace 'your-repository-name' with the name of your GitHub repository, or leave it empty if deploying to the user domain
